### ISSUE TITLE
Default To Search iTunes

### ISSUE THREAD

**Issue by say25** [cuappdev/podcast-ios#335]
**Problem Statement:**
As a user, I find it confusing that my popular podcasts that easily were found in my previous podcast app are hard to find. I can find them if I search iTunes.

**Alternatively Worded:**
As a user, I find it confusing that my popular podcasts that my friends are talking about are not in normal search results.

**Proposed Solution:**
Fire off two requests when searching for podcast data asynchronously to search iTunes as well as the other source.

**Comment by say25** [comment]
Maybe this and #327 are the same?

**Comment by natashaarmbrust** [comment]
Totally understandable. This is because our search algorithm is very naively implemented right now. We plan to implement elastic search in the next week so hopefully that will fix this issue. 

The issue with your proposed solution is that iTunes rate limits API calls. Thus, searching iTunes as a go-to is not a scalable solution. We really only use the search iTunes feature to crowdsource our database instead of scrapping every single series from iTunes.
